# Bridge connection
connection cloud-01
address [trocar pelo endereco hive]:8883
bridge_cafile /share/mosquitto/isrgrootx1.pem
topic electro/telemetry/song-pro-teste/data in 0
remote_username [trocar pelo usuario hive]
remote_password [trocar pela senha hive]
bridge_protocol_version mqttv311
try_private false
notifications false
bridge_attempt_unsubscribe false
bridge_insecure true
